name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Permite trigger manual

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout c√≥digo
      uses: actions/checkout@v4
    
    - name: Setup JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      env:
        SKIP_JDK_VERSION_CHECK: true
    
    - name: Build Debug APK
      run: |
        cd IPTVPlayer
        chmod +x gradlew
        ./gradlew assembleDebug --stacktrace
    
    - name: Upload APK Debug
      uses: actions/upload-artifact@v4
      with:
        name: iptv-player-debug
        path: IPTVPlayer/app/build/outputs/apk/debug/*.apk
    
    - name: Build Release APK
      run: |
        cd IPTVPlayer
        ./gradlew assembleRelease --stacktrace
      
    - name: Upload APK Release
      uses: actions/upload-artifact@v4
      with:
        name: iptv-player-release
        path: IPTVPlayer/app/build/outputs/apk/release/*.apk
